language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
install:
    - pip install coveralls --use-mirrors
# command to run tests
script:
  coverage run --source=osmwriter setup.py test
after_success:
  coveralls
